name: Build docker image & push to ghcr

on:
  push:
    branches:
      - master


permissions:
  contents: write
  packages: write

jobs:
  docker-local:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          push: true
          platforms: linux/amd64
          file: ./Dockerfile
          tags: ghcr.io/sigmagmbh/swisstronik-multisig-ui:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.ACTIONS_GITHUB_TOKEN }}
